# Numpy Assignment

# 1. What is a Python library? Why do we use Python libraries

Python Library:
A Python library is a collection of pre-written code that offers ready-made functions and tools to perform various tasks. We use Python libraries to save time, improve efficiency, promote code reusability, leverage specialized functionality for specific domains like data science and web development, benefit from community support, and tap into the open-source nature of the Python ecosystem.

 # 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store and manipulate collections of data, but they have some key differences. Here are the main distinctions:

1. Data Type:
In a NumPy array, all elements must be of the same data type. This homogeneity allows for more efficient storage and operations.
Lists in Python can contain elements of different data types, providing more flexibility but potentially leading to less efficient numerical operations.

2. Performance:
NumPy arrays are more efficient for numerical operations than Python lists. NumPy is implemented in C and optimized for performance, making operations on large datasets significantly faster compared to the equivalent operations on lists.
Lists are more general-purpose and not optimized for numerical computations, so they may be slower for tasks involving large amounts of numerical data.

3. Size:
NumPy arrays are more memory-efficient compared to lists, especially for large datasets. This is due to the homogeneity of data types and the optimized storage of elements.
Lists, being more flexible, may consume more memory because each element can be of a different data type.

4. Functionality:
NumPy provides a wide range of mathematical functions and operations that can be applied directly to entire arrays. These operations are vectorized, meaning they can be performed on entire arrays without the need for explicit loops.
Lists offer more general-purpose functionality but lack the specialized numerical operations provided by NumPy.

5. Syntax:
NumPy syntax is designed for array operations, and it supports multidimensional arrays. NumPy provides a variety of functions for array manipulation and mathematical operations.
Lists are part of the core Python language and have a more general syntax. They are commonly used for a wide range of purposes beyond numerical computing.

# 3. Find the shape, size and dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [1]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# Shape is
arr.shape

(3, 4)

In [10]:
# size is:
arr.size

12

In [11]:
# dimension is:
arr.ndim

2

Explanation:
1. to find shape we can use arr.shape function in numpy
2. for size we can use arr.size
3. for dimension use arr.ndim

# 4. Write python code to access the first row of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0]
# access first row

array([1, 2, 3, 4])

Explanation:
It's very easy to access first row of given array using row index like arr[0] here 0---> first row of array

# 5. How do you access the element at the third row and fourth column from the given numpy array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [19]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[2,3]
# or arr[2][3]

12

Explanation: 
1. to access element at third row and fourth column we generally used index like arr[2,3] or arr[2][3]

 # 6. Write code to extract all odd-indexed elements from the given numpy array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [20]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Explanation:
1. arr[:, 1::2] slices the array along the columns (:), starts from index 1 (odd-indexed) in each row, and takes every second      element (::2). 
2. This extracts all the odd-indexed elements along the columns in each row of the array.
    

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [9]:
np.random.rand(3,3)

array([[0.48682575, 0.95809537, 0.95469079],
       [0.21095567, 0.48025741, 0.14998178],
       [0.1685179 , 0.65952467, 0.67435186]])

Explanation: 
1. The np.random.rand() function generates an array of random numbers from a uniform distribution over the range [0, 1) .

2.  The arguments (3, 3) specify the shape of the array, resulting in a 3x3 matrix.

 # 8. Describe the difference between np.random.rand and np.random.randn?

In [22]:
# Generate a 2x3 array of random numbers between 0 and 1
random_array = np.random.rand(2, 3)
random_array

array([[0.03032729, 0.12729496, 0.1640224 ],
       [0.01563952, 0.59475468, 0.81434797]])

In [20]:
# Generate a 2x3 array of random numbers from a standard normal distribution
random_array = np.random.randn(2, 3)
random_array

array([[-0.62288676, -0.2931008 , -1.03162067],
       [ 0.8337448 ,  1.45884429,  0.13975847]])

Explanation:
1. np.random.rand generates random numbers from a uniform distribution over [0.0, 1.0) .

2. while np.random.randn generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

# 9. Write code to increase the dimension of the following array?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [33]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
# increase the dimension of arr1 using expand_dims()
arr2 = np.expand_dims(arr1,axis=0)
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [38]:
arr3 = np.expand_dims(arr2,axis=0)
arr3

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

Explanation: 
1. For increase the dimension of given array we can use np.expand_dims()
2. in above i will have to pass 2 data , first is array and second is axis

# 10. How to transpose the following array in NumPy?
 [[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [43]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
# Transpose of given matrix is
arr1.T
# we can use np.transpose(arr1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
np.transpose(arr1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Explanation:
1. The transposed array swaps the rows and columns of the original array.
2. for transpose we can use np.transpose() or arr.T both will transpose the origional array
    

#  11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]] 
Perform the following operation using Python
1. Index wise multiplicatio
2. Matrix multiplicatio
3. Add both the matric
4. Subtract matrix B from 
5. Divide Matrix B by A

In [49]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [50]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 1. Index wise multipication

In [52]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# 2. Matrix Multipication 

In [58]:
# Here for matrix multipication number of column in A matrix = number of row in B matrix,so let's Transpose of B
T_Of_B = B.T  # transpose of matrix B
A@T_Of_B
# we can use np.dot[A,B.T]


array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

# 3. Add both the matric

In [59]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

# 4. Subtract matrix B from 

In [60]:
B-A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 5. Divide Matrix B by A

In [61]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

 # 12.  Which function in Numpy can be used to swap the byte order of an array?

In [5]:
arr = np.array([[1,2,3],[4,5,6],[8,9,5]])

In [7]:
arr2 = arr.byteswap()
arr2

array([[ 16777216,  33554432,  50331648],
       [ 67108864,  83886080, 100663296],
       [134217728, 150994944,  83886080]])

Explanation:
1. In NumPy, you can use the byteswap() function to swap the byte order of    an array. 
2. This function creates a new array with the byte order swapped from the      original array. 
3. The byte order can be specified using the byteorder parameter.

# 13.  What is the significance of the np.linalg.inv function?
 

In [8]:
np.linalg.inv(arr)

array([[-1.93333333,  1.13333333, -0.2       ],
       [ 1.86666667, -1.26666667,  0.4       ],
       [-0.26666667,  0.46666667, -0.2       ]])

Explanation:
1. The np.linalg.inv() function in NumPy is used to compute the inverse of    a square matrix.
2. The significance of finding the inverse of a matrix lies in various        areas of mathematics and scientific computing, including solving systems    of linear equations, computing determinants, and solving certain            optimization problems.

# 14.  What does the np.reshape function do, and how is it used?

In [9]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [10]:
np.reshape(arr2,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

Explanation:
1. The np.reshape() function in NumPy is used to change the shape of an        array without changing its data.
2. It allows you to rearrange the elements of an array into a new shape        while maintaining the same total number of elements.

# 15. What is broadcasting in Numpy?

Broadcasting:
1. Broadcasting in NumPy is a mechanism that allows arrays with different      shapes to be combined and operated upon in arithmetic and other            mathematical operations.
2. It enables NumPy to perform element-wise operations between arrays of      different shapes without the need for explicit looping over the            elements.

In [12]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2 = np.array([3,3,3,3])

In [13]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2

array([3, 3, 3, 3])

In [15]:
arr1 + arr2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])